=== What is OpenGL?

OpenGL is a cross-platform graphics rendering API. It provides an abstract specification for GPU interactions, such as functions and constants that can be called from code. Because of that, OpenGL is language independent.

As mentioned, OpenGL only provides the definition of used functions. The implementation of said functions is fully delegated to the underlying <<Windowing System>>.

==== Comparison to other Rendering APIs

OpenGL is not the only graphics rendering API on the market. Nowadays there are several options for choosing a graphics API, the most popular ones being *DirectX* for Windows (developed by *Microsoft*), *Metal* for Apple operating systems such as iOS or macOS (developed by *Apple*), and Vulkan, which is meant to be the modern successor of OpenGL (developed by the non-profit *Khronos Group*).

.Popular Graphics APIs
[cols="1,1,3"]
|===
|Graphics API |Developer |Description

|OpenGL
|Khronos Group
|Easy-to-use, cross-plattform, cross-language Graphics Rendering API.

|DirectX
|Microsoft
|Low-level Graphics API for Windows

|Metal
|Apple
|Low-level Graphics API for Apple-based operating systems (iOS, macOS, iPadOS, tvOS)

|Vulkan
|Khronos Group
|Low-level, highly performant cross-plattform Graphics API. Successor of OpenGL

|===

.Basemark comparison of OpenGL, DirectX and Vulkan (Source: {author}, Data Source: link:https://www.guru3d.com/articles_pages/amd_radeon_rx_6800_xt_review,28.html[Basemark])
[graphviz_py, format=svg]
----
include::../diagrams/comparison.py.dot[]
----

=== Windowing System

==== My Cite
This is a citation. cite:[CRAFT]

==== A formula
latexmath:[\qquad \frac{a}{b} = 438]

// A page break
<<<

==== A table
.My new Table (Source: {author})
[cols="1,1"]
|===
|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2

|Cell in column 1, row 3
|Cell in column 2, row 3
|===

.My Python Code (Source: {author})
[source,python,linenums=implicit]
----
if True:
    print("Hello World")
----