name: Build thesis
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:1.16
    steps:
      - name: Install git lfs
        run: apk add --update --no-cache git-lfs python3 python3-dev py3-pip py3-numpy py3-numpy-dev gcc g++

      - name: Install asciidoctor-lists
        run: gem install asciidoctor-lists

      - name: Asciidoctor-diagrams patch
        run: git clone https://github.com/Alwinator/asciidoctor-diagram /tmp/asciidoctor-diagram

      - name: Update pip packages
        run: pip3 install --upgrade pip setuptools wheel

      - name: Install pip packages
        run: pip3 install diagrams graphviz-py
      
      - name: Create work directory
        run: mkdir -p /work/scripts && cd /work

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Copy project to work directory
        run: cp -r . /work

      - name: Copy build script to work directory
        run: cp ./paper/scripts/asciidoc-to-pdf.sh /work/scripts/asciidoc-to-pdf.sh

      - name: ls
        run: cd /work

      - name: Create build directory
        run: mkdir -p ./paper/build
        working-directory: /work

      - name: Build PDF
        run: chmod +x ./scripts/asciidoc-to-pdf.sh && ./scripts/asciidoc-to-pdf.sh
        shell: bash
        working-directory: /work

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: /work/paper/build
